In [40]:
import tensorflow as tf
import pandas as pd
import numpy as np
import torch
import os

## 2

### a

In [78]:
def SNN(X,W,b):
    IN=X@W+b
    return 1/(1+tf.exp(-IN))

In [79]:
X=torch.tensor([[1.0,2.0],[-1.0,2.0],[-2.0,1.0],[0.0,1.0]],dtype=torch.float32)
W=torch.tensor([[-1.0,0.5,1.0],[1.0,0.0,-0.5]],dtype=torch.float32)
b=torch.tensor([[0.0,1.0,2.0]],dtype=torch.float32)

### b

In [80]:
print(SNN(X,W,b))

tf.Tensor(
[[0.7310586  0.81757444 0.880797  ]
 [0.95257413 0.62245935 0.5       ]
 [0.95257413 0.5        0.37754068]
 [0.7310586  0.7310586  0.81757444]], shape=(4, 3), dtype=float32)


## 3
abc

In [178]:
def ndf(X,u,sig):
    log_term=torch.log(np.pi*2*sig**2)
    sec_term=(X-u)/sig
    return -(sec_term**2+log_term)/2

In [183]:
X=torch.tensor([-1,0,1,2],dtype=torch.float32)
u=torch.tensor(1,dtype=torch.float32)
sig=torch.tensor(2,dtype=torch.float32)
print(ndf(X,u,sig))

tensor([-2.1121, -1.7371, -1.6121, -1.7371])


## 4

### a

In [188]:
def g_eta(eta):
    return torch.log(1+torch.exp(eta))

In [194]:
def NLL(X,u,eta):
    sig=g_eta(eta)
    return -torch.sum(ndf(X,u,sig))


### b

In [202]:
X=torch.tensor([-1,0,1,2],dtype=torch.float32,requires_grad=True)
u=torch.tensor(1,dtype=torch.float32,requires_grad=True)
eta=torch.tensor(0,dtype=torch.float32,requires_grad=True)
print(NLL(X,u,eta))


tensor(8.4538, grad_fn=<NegBackward0>)


### c

In [210]:
def NLL_grad(X,u,eta):
    sig=g_eta(eta)
    loss=-torch.sum(ndf(X,u,sig))
    loss.backward()
    deta=eta.grad
    dmu=u.grad
    return deta,dmu


In [211]:
deta,dmu=NLL_grad(X,u,eta)
print(deta,dmu)

tensor(-6.1230) tensor(4.1627)
